### ISSUE TITLE
Client index 0 is invalid

### ISSUE THREAD

**Issue by gijsroge** [alongubkin/store#6]
Latest dev version outputs this error. If I type !store (nothing happens)

```
L 09/19/2013 - 20:52:17: [SM] Native "IsClientInGame" reported: Client index 0 is invalid
L 09/19/2013 - 20:52:17: [SM] Displaying call stack trace for plugin "store-core.smx":
L 09/19/2013 - 20:52:17: [SM]   [0]  Line 131, C:\Users\root\Desktop\Jail\cstrike\addons\sourcemod\scripting\store-core.sp::OnClientSayCommand()
```

**Comment by alongubkin** [comment]
https://github.com/alongubkin/store/commit/14b3017019717526a9dd55f51d967e17563db0dc

**Comment by alongubkin** [comment]
Sorry, that was a mistake on my side. Anyway I fixed it in the dev branch.

**Comment by gijsroge** [comment]
No problem :)
Error still pops up tho. And !store doesn't do anything either.

```
L 09/19/2013 - 23:04:45: [SM] Native "IsClientInGame" reported: Client index 0 is invalid
L 09/19/2013 - 23:04:45: [SM] Displaying call stack trace for plugin "store-core.smx":
L 09/19/2013 - 23:04:45: [SM]   [0]  Line 134, C:\Users\root\Desktop\Jail\cstrike\addons\sourcemod\scripting\store-core.sp::OnClientSayCommand()
```

**Comment by alongubkin** [comment]
Oops, fixed the "Client index 0 is invalid" properly here:
https://github.com/alongubkin/store/commit/c6e926e3f3170831fcaf0ebb8d564a65c08a12f5

I'll check why the chat command doesn't work tomorrow, even though eggsampler will probably solve it long before me.

**Comment by gijsroge** [comment]
Haha, awsome thanks :)

Error is fixed indeed.

**Comment by gijsroge** [comment]
Chat command doesn't work indeed. Nothing happens , no error logs or anything

**Comment by eggsampler** [comment]
I haven't been super stringent on testing changes in the development brach as of yet (hence development). Tbh the only reason I'm pushing commits to GitHub is to encourage input and let people know its slowly coming along. I will in fact edit the readme to display in big words on the dev branch that here be dragons and there's a good chance it won't work unless you know what you're doing. 

Will be looking into this, but I would recommend not using this branch on any servers.

**Comment by gijsroge** [comment]
You say that you use github to get input? This is feedback? I don't understand :P You probably don't want noobs to create unnecessary issues which I understand. Anyway we have been facing issues with the 1.2 & alpha version that rendered the store useless in our case. The editor to position our items stored that json attr the other way around (first angles than position) and store couldn't handle that and stopped working. So i have been hopelessly trying out every update hoping it would be solved and we could start on positioning our items.

To give you an idea you can take a look at our Store Itemviewer-> http://items.dimension-gaming.com/ 
Our server opening is completley dependent on store so you could understand why i have been trying out every update hehe.

**Comment by alongubkin** [comment]
The order of the JSON shouldn't matter. The other editor issue you've mentioned has been fixed here: 
https://github.com/alongubkin/store-equipment/commit/628dd1a5995d80c48e30eea43650acf1e99054a1

I'll work on the chat command now, but please don't post anymore issues about equipment in this thread or in this repo (as there's the store-equipment repo).

Also, you should know that I plan on releasing 1.2-beta in the next couple of days, so you might want to wait a bit. Your feedback is highly appreciated though!

**Comment by gijsroge** [comment]
Any progress? Its been a few weeks since the last commit.

**Comment by alongubkin** [comment]
Sorry, I"ve been very busy lately.

**Comment by gijsroge** [comment]
You have any idea when you will continue to work on it? Our server is waiting for a working version of store and equipment editor. :)
